### ISSUE TITLE
ingress support

### ISSUE THREAD

**Issue by masterkain** [Joxit/helm-charts#1]
any particular reason I don't see an ingress resource? https://github.com/Joxit/docker-registry-ui/blob/f0c72328431a2d16c298e9e221e6411943e7bfd7/examples/helm/docker-registry-ui/values.yaml#L42

**Comment by Joxit** [comment]
Hi, thank you for using my projects.

I did a full rework of the old helm chart and I thought that in general we should manage the ingress with our own stack (istio, traefik, consul ingress gateway...) and this will manage the SSL and redirect to the UI

Do you think this is something that may be added?

**Comment by masterkain** [comment]
based on my experience a helm chart like this might benefit from having an ingress template :)
but on the other hand it's not mandatory, if that's the case maybe a little mention in the readme goes a long way 👍 thanks!

**Comment by Joxit** [comment]
Hi, you were right, this is a good idea anyway
So I made a PR in order to add the support to ingress if you can take a look :smile:
