### ISSUE TITLE
Deleting of images in the registry - how to enable that feature?

### ISSUE THREAD

**Issue by cbachmann987** [Joxit/helm-charts#14]
I just installed your chart with internal registry - so far working fine.

What I did not get working was the deletion of images in the registry. "The Operation is unsupported"

I think I would need to add the environment variable 

```yaml
- name: REGISTRY_STORAGE_DELETE_ENABLED
  value: "true"
```

to the extraEnv: field.

This ends up in "json: cannot unmarshal array into Go struct field EnvVar.spec.template.spec.containers.env.value of type string" regardless if I put "true", 'true' or true in the value field above..

Any ideas? Somehow the chart does not allow boolean values here.

Thanks in advance for your help - if I need to provide anything else, please let me know

**Comment by Joxit** [comment]
Hello,

Thank you for using mu project and submitting issues :smile: 

I tried your example and got this message instead of yours : 
```
json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

I've just release the 1.1.2 with this fix, IDK if it will also fix your issue :shrug:  try it out 

```yaml
registry:
  enabled: true
  extraEnv:
    - name: REGISTRY_STORAGE_DELETE_ENABLED
      value: "true"
```

I've  automatically added this configuration when  `ui.deleteImages: true` in 1.1.2

**Comment by cbachmann987** [comment]
Thanks for your quick answer - I can confirm that with the fix you applied it works as expected.

Linking this setting to `ui.deleteImages: true` is a good idea - I had that in mind as well, but forgot to mention.

**Comment by Joxit** [comment]
Great! Thank you again, I will close the issue then :smile:
