### ISSUE TITLE
Bug in helm chart docs

### ISSUE THREAD

**Issue by jan-tee** [Joxit/helm-charts#9]
Helm chart docs say `ui.ingress.enable` is the key, but it is `ui.ingress.enabled`.

Maybe you can use a tool like `helm-docs` to auto-genereate the docs and prevent this from happening going forward

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues.

I fixed the doc and thank you again for the tips, I will try helm-docs  :wink:
